apiVersion: v1
kind: Service
metadata:
  name: {{ include "mockingbird.fullname" . }}
  labels:
    {{- include "mockingbird.labels" . | nindent 4 }}
spec:
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
      name: ssh
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-web
    - port: 8090
      protocol: TCP
      targetPort: 8090
      name: http-api
  selector:
    kubevirt.io/vm: {{ include "mockingbird.fullname" . }}
  type: ClusterIP
